# Generated by Django 4.2.5 on 2023-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('GPUChip', models.CharField(max_length=120)),
                ('Released', models.DateTimeField(default=None, null=True)),
                ('Bus', models.CharField(max_length=255)),
                ('Memory', models.CharField(max_length=255)),
                ('GPUclock', models.CharField(max_length=255)),
                ('Memoryclock', models.CharField(max_length=255)),
                ('Shaders_TMUs_ROPs', models.CharField(max_length=255)),
                ('URL', models.URLField()),
            ],
        ),
    ]
