# Generated by Django 4.2.5 on 2023-10-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0002_gpulist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulist',
            name='Released',
            field=models.DateField(default=None, null=True),
        ),
    ]
