# Generated by Django 4.2.6 on 2023-10-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0003_alter_gpulist_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='GPU Name')),
                ('variant', models.CharField(max_length=100, verbose_name='GPU Variant')),
                ('architecture', models.CharField(max_length=100, verbose_name='Architecture')),
                ('foundry', models.CharField(max_length=100, verbose_name='Foundry')),
                ('process_size', models.CharField(max_length=20, verbose_name='Process Size')),
                ('transistors', models.IntegerField(verbose_name='Transistors')),
                ('density', models.CharField(max_length=20, verbose_name='Density')),
                ('die_size', models.CharField(max_length=20, verbose_name='Die Size')),
                ('chip_package', models.CharField(max_length=100, verbose_name='Chip Package')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('generation', models.CharField(max_length=100, verbose_name='Generation')),
                ('predecessor', models.CharField(max_length=100, verbose_name='Predecessor')),
                ('successor', models.CharField(max_length=100, verbose_name='Successor')),
                ('production', models.CharField(max_length=100, verbose_name='Production')),
                ('launch_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Launch Price')),
                ('bus_interface', models.CharField(max_length=100, verbose_name='Bus Interface')),
                ('gpu_clock', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='GPU Clock')),
                ('memory_clock', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Memory Clock')),
                ('memory_size', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Memory Size')),
                ('memory_type', models.CharField(max_length=100, verbose_name='Memory Type')),
                ('memory_bus', models.CharField(max_length=20, verbose_name='Memory Bus')),
                ('bandwidth', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Bandwidth')),
                ('shading_units', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Shading Units')),
                ('tmus', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='TMUs')),
                ('rops', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ROPs')),
                ('compute_units', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Compute Units')),
                ('l1_cache', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='L1 Cache')),
                ('l2_cache', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='L2 Cache')),
                ('pixel_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pixel Rate')),
                ('texture_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Texture Rate')),
                ('fp32_performance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='FP32 (float)')),
                ('fp64_performance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='FP64 (double)')),
                ('slot_width', models.CharField(max_length=100, verbose_name='Slot Width')),
                ('length', models.CharField(max_length=20, verbose_name='Length')),
                ('tdp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='TDP')),
                ('suggested_psu', models.CharField(max_length=100, verbose_name='Suggested PSU')),
                ('outputs', models.CharField(max_length=100, verbose_name='Outputs')),
                ('power_connectors', models.CharField(max_length=100, verbose_name='Power Connectors')),
                ('board_number', models.CharField(max_length=100, verbose_name='Board Number')),
                ('directx', models.CharField(max_length=20, verbose_name='DirectX')),
                ('opengl', models.CharField(max_length=20, verbose_name='OpenGL')),
                ('opencl', models.CharField(max_length=20, verbose_name='OpenCL')),
                ('vulkan', models.CharField(max_length=20, verbose_name='Vulkan')),
                ('shader_model', models.CharField(max_length=20, verbose_name='Shader Model')),
            ],
            options={
                'verbose_name_plural': 'GPUs',
            },
        ),
        migrations.AlterModelOptions(
            name='gpulist',
            options={'ordering': ['ProductName']},
        ),
        migrations.AddField(
            model_name='gpulist',
            name='gpu_specs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpu.gpu', verbose_name='GPU'),
        ),
    ]
