# Generated by Django 4.2.6 on 2023-10-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0004_gpu_alter_gpulist_options_gpulist_gpu_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpulist',
            name='gpu_specs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gpu.gpu', verbose_name='GPU'),
        ),
    ]
