# Generated by Django 4.2.6 on 2023-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0005_alter_gpulist_gpu_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='transistors',
            field=models.CharField(max_length=100, verbose_name='Transistors'),
        ),
    ]
