# Generated by Django 4.2.6 on 2023-10-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0006_alter_gpu_transistors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='compute_units',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='successor',
        ),
        migrations.AlterField(
            model_name='gpu',
            name='bandwidth',
            field=models.CharField(max_length=100, verbose_name='Bandwidth'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='fp32_performance',
            field=models.CharField(max_length=100, verbose_name='FP32 (float)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='fp64_performance',
            field=models.CharField(max_length=100, verbose_name='FP64 (double)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_clock',
            field=models.CharField(max_length=100, verbose_name='GPU Clock'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='l1_cache',
            field=models.CharField(max_length=100, verbose_name='L1 Cache'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='l2_cache',
            field=models.CharField(max_length=100, verbose_name='L2 Cache'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='launch_price',
            field=models.CharField(max_length=100, verbose_name='Launch Price'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_size',
            field=models.CharField(max_length=100, verbose_name='Memory Size'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='pixel_rate',
            field=models.CharField(max_length=100, verbose_name='Pixel Rate'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.CharField(max_length=100, verbose_name='TDP'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='texture_rate',
            field=models.CharField(max_length=100, verbose_name='Texture Rate'),
        ),
    ]
