# Generated by Django 4.2.6 on 2023-10-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0007_remove_gpu_compute_units_remove_gpu_predecessor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory_clock',
            field=models.CharField(max_length=100, verbose_name='Memory Clock'),
        ),
    ]
