# Generated by Django 4.2.6 on 2023-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0008_alter_gpu_memory_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='board_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Board Number'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='foundry',
            field=models.CharField(max_length=100, null=True, verbose_name='Foundry'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='generation',
            field=models.CharField(max_length=100, null=True, verbose_name='Generation'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='launch_price',
            field=models.CharField(max_length=100, null=True, verbose_name='Launch Price'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='power_connectors',
            field=models.CharField(max_length=100, null=True, verbose_name='Power Connectors'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='production',
            field=models.CharField(max_length=100, null=True, verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='suggested_psu',
            field=models.CharField(max_length=100, null=True, verbose_name='Suggested PSU'),
        ),
    ]
