# Generated by Django 4.2.6 on 2023-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0009_alter_gpu_board_number_alter_gpu_foundry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='architecture',
            field=models.CharField(max_length=100, null=True, verbose_name='Architecture'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='bandwidth',
            field=models.CharField(max_length=100, null=True, verbose_name='Bandwidth'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='chip_package',
            field=models.CharField(max_length=100, null=True, verbose_name='Chip Package'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='density',
            field=models.CharField(max_length=20, null=True, verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='die_size',
            field=models.CharField(max_length=20, null=True, verbose_name='Die Size'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='directx',
            field=models.CharField(max_length=20, null=True, verbose_name='DirectX'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='fp32_performance',
            field=models.CharField(max_length=100, null=True, verbose_name='FP32 (float)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='fp64_performance',
            field=models.CharField(max_length=100, null=True, verbose_name='FP64 (double)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_clock',
            field=models.CharField(max_length=100, null=True, verbose_name='GPU Clock'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='l1_cache',
            field=models.CharField(max_length=100, null=True, verbose_name='L1 Cache'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='l2_cache',
            field=models.CharField(max_length=100, null=True, verbose_name='L2 Cache'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='length',
            field=models.CharField(max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_bus',
            field=models.CharField(max_length=20, null=True, verbose_name='Memory Bus'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_clock',
            field=models.CharField(max_length=100, null=True, verbose_name='Memory Clock'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_size',
            field=models.CharField(max_length=100, null=True, verbose_name='Memory Size'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Memory Type'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='opencl',
            field=models.CharField(max_length=20, null=True, verbose_name='OpenCL'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='opengl',
            field=models.CharField(max_length=20, null=True, verbose_name='OpenGL'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='outputs',
            field=models.CharField(max_length=100, null=True, verbose_name='Outputs'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='pixel_rate',
            field=models.CharField(max_length=100, verbose_name='Pixel Rate, null=True'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='process_size',
            field=models.CharField(max_length=20, null=True, verbose_name='Process Size'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='rops',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='ROPs'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='shader_model',
            field=models.CharField(max_length=20, null=True, verbose_name='Shader Model'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='shading_units',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Shading Units'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='slot_width',
            field=models.CharField(max_length=100, null=True, verbose_name='Slot Width'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.CharField(max_length=100, null=True, verbose_name='TDP'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='texture_rate',
            field=models.CharField(max_length=100, null=True, verbose_name='Texture Rate'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tmus',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='TMUs'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='transistors',
            field=models.CharField(max_length=100, null=True, verbose_name='Transistors'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='variant',
            field=models.CharField(max_length=100, null=True, verbose_name='GPU Variant'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vulkan',
            field=models.CharField(max_length=20, null=True, verbose_name='Vulkan'),
        ),
    ]
