# Generated by Django 4.2.6 on 2023-10-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0010_alter_gpu_architecture_alter_gpu_bandwidth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='boost_clock',
            field=models.CharField(max_length=100, null=True, verbose_name='Boost Clock'),
        ),
        migrations.AlterField(
            model_name='gpulist',
            name='gpu_specs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='gpu.gpu', verbose_name='GPU'),
        ),
    ]
