# Generated by Django 4.2.6 on 2023-10-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0011_gpu_boost_clock_alter_gpulist_gpu_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='bus_interface',
            field=models.CharField(max_length=100, null=True, verbose_name='Bus Interface'),
        ),
    ]
