# Generated by Django 4.2.6 on 2023-10-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu', '0012_alter_gpu_bus_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='GPU Name'),
        ),
    ]
